name: authflow
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^1.5.0
  go_router: ^6.2.0
  uuid: ^3.0.7
  crypto: ^3.0.2
  jwt_decode: ^0.3.1
  sign_in_with_apple: ^4.3.0
  flutter_appauth: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
